<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
	   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml" lang="en_US" xml:lang="en_US">
	<head>
		<title>Ouray</title>
		<link rel="stylesheet" href="/resources/style.css" type="text/css" media="all" />		
		<link rel="stylesheet" href="/resources/viewCourse.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/resources/jquery.autocomplete.css" type="text/css" media="all" />
		<link rel="stylesheet" href="/resources/ajax.css" type="text/css" media="all" />		

	</head>
	<body>
		<div id="headerColor">
			<div id="headerLogin">
				<?php include("includes/loginBox.phtml"); ?>
			</div>		
		</div>
		
		<div id="footerColor">
		
			<div id="mainContent">
			
				<h1><a href="/">Ouray</a> Oops!</h1>
				
				<p>You must be a member of sneffel to do that, why don't you login now?</p>
				<?php include("includes/loginBox.phtml"); ?>
				</div>
<?php include "copyright.inc.phtml" ?>	
		</div>
		


		
	</body>
</html>
